---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/shortened_urls":
    post:
      summary: Creates the shortened URL
      tags:
      - shortened url
      parameters: []
      responses:
        '201':
          description: shortened url created
        '422':
          description: url is invalid
      requestBody:
        content:
          application/json:
            schema:
              properties:
                url:
                  type: string
              required:
              - url
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
